### ISSUE TITLE
Unable to use agent package with meteor-apm-server

### ISSUE THREAD

**Issue by DeanKamali** [lmachens/meteor-apm-server#48]
I have setup server via docker image

I tried connecting my app after running `meteor add meteorhacks:kadira` it added two packages to my project 

```
meteorhacks:kadira   added, version 2.30.4    
meteorhacks:meteorx  added, version 1.4.1
```
Then my application doesn't want to start, is there is a specific meteor-apm-server agent I could use instead? 
```
=> Started proxy.                             
W20200428-12:32:07.569(-4)? (STDERR) /Users/dean/.meteor/packages/meteor-tool/.1.10.2.szrfc1.fymg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20200428-12:32:07.605(-4)? (STDERR)                                            throw(ex);
W20200428-12:32:07.605(-4)? (STDERR)                                            ^
W20200428-12:32:07.606(-4)? (STDERR) 
W20200428-12:32:07.606(-4)? (STDERR) TypeError: Cannot read property 'constructor' of undefined
W20200428-12:32:07.606(-4)? (STDERR)     at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
W20200428-12:32:07.606(-4)? (STDERR)     at exposeLivedata (packages/meteorhacks_meteorx.js:31:5)
W20200428-12:32:07.606(-4)? (STDERR)     at packages/meteorhacks_meteorx.js:175:1
W20200428-12:32:07.606(-4)? (STDERR)     at packages/meteorhacks_meteorx.js:200:4
W20200428-12:32:07.607(-4)? (STDERR)     at packages/meteorhacks_meteorx.js:208:3
W20200428-12:32:07.607(-4)? (STDERR)     at /Users/dean/Projects/swiftdental/.meteor/local/build/programs/server/boot.js:401:38
W20200428-12:32:07.607(-4)? (STDERR)     at Array.forEach (<anonymous>)
W20200428-12:32:07.608(-4)? (STDERR)     at /Users/dean/Projects/swiftdental/.meteor/local/build/programs/server/boot.js:226:21
W20200428-12:32:07.608(-4)? (STDERR)     at /Users/dean/Projects/swiftdental/.meteor/local/build/programs/server/boot.js:464:7
W20200428-12:32:07.608(-4)? (STDERR)     at Function.run (/Users/dean/Projects/swiftdental/.meteor/local/build/programs/server/profile.js:280:14)
W20200428-12:32:07.608(-4)? (STDERR)     at /Users/dean/Projects/swiftdental/.meteor/local/build/programs/server/boot.js:463:13
```

Thanks

**Comment by anthonny** [comment]
Hi @DeanKamali 
It works for me with the monti agent:
`meteor add montiapm:agent`

I run `meteor-apm-server` locally like this:
`meteor --port 4000 --settings settings.json`

With this `settings.json`:
```
❯ cat settings.json                                                                                                                
{
  "metricsLifetime": 604800000,
  "public": {
    "apmEngineUrl": "http://localhost:4000"
  }
}
```

And in my meteor application, I define these env vars:
```
MONTI_APP_ID=yHbBh4nkv5HcZYcQ7
MONTI_APP_SECRET=rc7aFLC8MQ4Xgi9ir
MONTI_OPTIONS_ENDPOINT=http://localhost:11011
```

**Comment by DeanKamali** [comment]
Works great! thank you

Here is my docker-compose file for reference 
```
cat > docker-compose.yaml << EOL
    version: '3.3'
    services:
        meteor-apm-server:
            container_name: meteor-apm-server
            ports:
                - '4000:80'
                - '7007:7007'
                - '11011:11011'
            environment:
                - PORT=80
                - 'MONGO_URL=mongodb://mongo'
                - 'MONGO_OPLOG_URL=mongodb://mongo'
                - 'ROOT_URL=http://localhost'
            image: 'strictlyskyler/meteor-apm-server:1.1.0'
            links:
                - mongo
        mongo:
            image: mongo
            restart: always
            volumes:
                - ./data:/data/db
EOL
```

`mkdir data`
`docker-compose up -d`
